config/routes.rb
Cakeday::Application.routes.draw do

  get "cakes/new"
  get "cakes/create"
  get "cakes/destroy"
  match 'cakes/:id/give', to: 'cakes#give', via: 'get'
  resources :users
  resources :cakes
  resources :sessions, only: [:new, :create, :destroy]
  get "users/new"
  root 'static_pages#registration'

  match 'users/:id/location', to: 'users#map', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/users', to: 'users#index', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/cakes/:id/transfercake', to: 'cakes#transfercake', via: 'patch'

end

app/models/cake.rb
class Cake < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('updated_at DESC') }
	validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cakes

	before_create :create_remember_token
  # before_create :init

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, length: {minimum: 6}
  has_secure_password

  def init
    self.happiness ||= 1.0
  end

  def User.new_remember_token
  	SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


    private
      def create_remember_token
        self.remember_token = User.digest(User.new_remember_token)
      end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cakes_controller.rb
require 'pry'
class CakesController < ApplicationController
  before_action :signed_in_user
 
  def create #hash includes key-value pairs of flavors and their images
    flavors = {"chocolate" => "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSJNaRrW7SntN3pqaYY2pEVSOZQRPZlM9WKpLXLrPWPNZXgdp46", 
      "vanilla" => "http://sweetclipart.com/multisite/sweetclipart/files/imagecache/middle/food_holidays_birthday_cake_2_with_candles_vanilla.png", 
      "strawberry" => "http://www.foodclipart.com/food_clipart_images/strawberry_cake_0071-0905-1905-0551_SMU.jpg", 
      "coffee" => "http://thumbs.gograph.com/gg59190493.jpg", 
      "ice cream" => "http://www.uncleharrysicecream.com/images/clipart-cake-and-ice-cream-lg.jpg", 
      "cheese" => "http://www.musthavemenus.com/imageservice/images/13/m0703212aa/img_large_watermarked.jpg",
      "birthday" => "http://cakepic4u.com/wp-content/uploads/2014/05/birthday-cakes-pictures-clip-art-4.jpg"}
  	this_flavor = flavors.keys.sample
    @cake = current_user.cakes.build(flavor: this_flavor, 
  		message: "", 
  		user_id: current_user.id, 
      has_been_given: false, 
      baked_by: current_user.name, 
      photo: flavors[this_flavor] )
  	  if @cake.save
  	  	flash[:success] = "Your Cake is Baked :)"
		    redirect_to current_user
	  else
	  	render 'static_pages/help'
	  end
  end

  def destroy
  end

  def give
    @cakes = current_user.cakes.where("has_been_given = ?", false)
  end

  def transfercake #essentially, subtract one from giver and add one to receiver
    @cake = current_user.cakes.find(params[:cake_id])
    if (@cake == nil)
       flash[:been_given] = "You don't have any cakes to give."
       redirect_to "/users/" + current_user.id.to_s
    elsif current_user.cakes.count > 0 
      @cake.update_attributes!(user_id: params[:id], has_been_given: true, message: params[:message])
      current_user.update_attribute(:happiness, (current_user.happiness + 1.0)) #happiness is increased when giving cake
      User.find(params[:id]).update_attribute(:happiness, (User.find(params[:id]).happiness + 0.5)) #happiness is increased by smaller margin when receiving cake
      redirect_to "/users/" + params[:id]
    else
      flash[:no_more_cakes] = 'You have no more cakes to give.'
      redirect_to "/users/" + current_user.id.to_s
    end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user

		else
			flash.now[:error] = 'Invalid email/password combo, dawg!'
			render 'new'
		end
	end

	def new
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def registration
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  

  def index
    @users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to CakeDay!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
  	@user = User.find(params[:id])
  	@cake = current_user.cakes.build if signed_in?
  end

  def map
    @zoom = (21 - ((current_user.happiness.to_i)*0.3).to_i).to_s #21 is the maximum zoom level for Google Maps API. The greater the happiness, the more the map is zoomed OUT (and the bigger the user looks)
    if @zoom.to_i < 0 #applies limit to how large the map is allowed to get
      @zoom = 0.to_s
    end
  end

private 

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "CakeDay"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


	def sign_in(user)
	    remember_token = User.new_remember_token
	    cookies.permanent[:remember_token] = remember_token
	    user.update_attribute(:remember_token, User.digest(remember_token))
	    self.current_user = user 
	end

	def current_user=(user)
		@current_user = user
	end

    def current_user
      remember_token = User.digest(cookies[:remember_token])
      @current_user ||= User.find_by(remember_token: remember_token)
    end

    def signed_in?
    	!current_user.nil?
    end

    def signed_in_user
    	unless signed_in?
    		redirect_to signin_url, notice: "Please sign in."
    	end
    end

    def sign_out
    	current_user.update_attribute(:remember_token, 
    		User.digest(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cakes/create.html.erb
<h1>Cakes#create</h1>
<p>Find me in app/views/cakes/create.html.erb</p>

app/views/cakes/destroy.html.erb
<h1>Cakes#destroy</h1>
<p>Find me in app/views/cakes/destroy.html.erb</p>

app/views/cakes/give.html.erb
<h1>Your cakes!</h1>

<% @cakes.each do |cake| %>
	
	<img src=<%= cake.photo %> width="150" height="150">

	<%= form_tag "/cakes/" + params[:id] + "/transfercake", method: "patch" do %>
		<%= label_tag("Send a message!") %> <%= text_area_tag(:message) %>
		<%= hidden_field_tag "cake_id", cake.id %>
		<%= submit_tag("Give this cake! :)") %>

	<% end %> <br>

	

<% end %>

app/views/cakes/new.html.erb
<h1>Cakes#new</h1>
<p>Find me in app/views/cakes/new.html.erb</p>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <% if signed_in? %>
            <%= link_to "CakeDay", current_user, id: "logo" %>
          <% else %>
            <%= link_to "CakeDay", root_path, id: "logo" %>
          <% end %>
          <nav>
            <ul class="nav pull-right">
              
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "About", about_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Registration",    root_path %></li>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>              
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="whole-page">
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%>

<h1>About this app</h1>
<p>Share cakes with your friends with CakeDay. Cakes for everyone!</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>Help</h1>
<p>For help with this app, contact David McPeek or Nikki Feldman.</p>

app/views/static_pages/registration.html.erb
<div class="center hero-unit">
  <h1>Sign up here</h1>

  <h2>
    This is the home page for CakeDay.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<%= link_to user.name, user %> <br>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>

<%= render @users %>

app/views/users/map.html.erb
Your happiness meter reads: <%= current_user.happiness %> <br>


<img src= "http://maps.googleapis.com/maps/api/staticmap?
center=17+Hillhouse+Avenue,New+Haven,+CT&
zoom=<%= @zoom %>&
size=900x450&
scale=2&
maptype=terrain&
markers=icon:http://docs.geoserver.org/stable/en/user/_images/smileyface1.png?
chst=d_map_pin_icon%26chld=smiley%257C996600%7C17+Hillhouse+Avenue,New+Haven,+CT">

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>   

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>


      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

<div class="span9">
<div class="span3" id="username">
<h2><%= @user.name %></h2>

<% if current_user == @user %>
<%= link_to "Happiness map.", '/users/' + current_user.id.to_s + '/location' %> <br>
<% end %>

<% if current_user == @user %>
<%= form_for(@cake) do |f| %>
     <%= f.submit "Bake a cake!", class: "btn btn-large btn-primary" %>
<% end %>

	<% else %>

	<%= form_tag "/cakes/" + params[:id] + "/give", method: "get" do %>

		<%= submit_tag "Give " + @user.name + " a cake!", class: "btn btn-large btn-primary" %>
	<% end %>

<% end %>
</div>


<div class="span5" id="happiness">
<br>
Happiness meter: <br> <%= @user.happiness %>
</div>




<div id="received" class="span7">
<h2 id="received-header"> Cakes <%= @user.name%> has received: </h2>
<% @user.cakes.where("has_been_given = ?", true).each do |cake| %>
	<img src=<%= cake.photo %> width="50" height="50">
	<% if cake.message.blank? %>
	<% else %>
		"<%= cake.message %>"
	<% end %>
		From: <%= cake.baked_by %>
	<br> <br>
<% end %>
</div>
</div>


<div id="baked" class="span3">
Cakes <%= @user.name%> baked: <br> <br>
<% @user.cakes.where("has_been_given = ?", false).each do |cake| %>
	<img src=<%= cake.photo %> width=25px height=25px >
<% end %>
</div> 

<a href="https://www.facebook.com/events/1456381854611534/?fref=ts">International Cake Day Facebook app</a>
<br>
</div>